services:
  db:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: local_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sito/DB:/docker-entrypoint-initdb.d
    networks:
      - rete_sito

  web:
    build: .
    container_name: app_web_local
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=local_user
      - DB_PASSWORD=password
      - DB_NAME=my_database
    depends_on:
      - db
    networks:
      - rete_sito

volumes:
  db_data:

networks:
  rete_sito:
    driver: bridge